language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - black --check .
  - flake8 .

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-west-2"
  app: "django-tutorial1"
  env: "django-env1"
  bucket_name: "elasticbeanstalk-us-west-2-851725369846"
  on:
    repo: "samkitshah18/swe1-app"
    branch: "main"